create table circ_trans(
	id integer not null distkey,
	patron_id integer,
	patron_record_id bigint,
	item_id integer,
	item_record_id bigint,
	bib_id integer,
	bib_record_id bigint,
	volume_record_id bigint,
	transaction_gmt timestamptz not null sortkey,
	application_name varchar(200),
	source_code  varchar(200),
	op_code varchar(5),
	stat_group_code_num smallint,
	due_date_gmt timestamptz,
	count_type_code_num smallint,
	itype_code_num smallint,
	icode1 integer,
	icode2 varchar(5),
	item_location_code varchar(20),
	item_agency_code_num smallint,
	ptype_code varchar(5),
	pcode1 varchar(5),
	pcode2 varchar(5),
	pcode3 smallint,
	pcode4 smallint,
	patron_home_library_code varchar(20),
	patron_agency_code_num smallint,
	loanrule_code_num smallint
);
